server:
  port: 8081
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.11.124:3306/oauth2?createDatabaseIfNotExist=true
    username: