INSERT INTO `client` VALUES (1, 600, 'ADMIN,USER,SUPERADMIN', 'authorization_code,password,client_credentials,refresh_token,implicit', 'admin', '$2a$10$YBnfqylX69Uh/w8diub41ulfpywrKPFVis3BqsQSgobnpSC0283j.', 3600, 'http://10.10.11.50:8001/callback?uuid=', '', '');
INSERT INTO `client_to_resource` VALUES (1, 1);
INSERT INTO `client_to_resource` VALUES (1, 2);
INSERT INTO `client_to_resource` VALUES (1, 3);
INSERT INTO `client_to_scope` VALUES (1, 1);
INSERT INTO `client_to_scope` VALUES (1, 2);
INSERT INTO `client_to_scope` VALUES (1, 3);
INSERT INTO `resource` VALUES (1, 'demo');
INSERT INTO `resource` VALUES (2, 'test');
INSERT INTO `resource` VALUES (3, 'dev');
INSERT INTO `resource` VALUES (4, 'demo');
INSERT INTO `resource` VALUES (5, 'test');
INSERT INTO `resource` VALUES (6, 'dev');
INSERT INTO `role` VALUES (1, 'ADMIN', '管理员');
INSERT INTO `role` VALUES (2, 'USER', '普通用户');
INSERT INTO `role` VALUES (3, 'SUPERADMIN', '超级管理员');
INSERT INTO `role` VALUES (4, 'ADMIN', '管理员');
INSERT INTO `role` VALUES (5, 'USER', '普通用户');
INSERT INTO `role` VALUES (6, 'SUPERADMIN', '超级管理员');
INSERT INTO `scope` VALUES (1, 'all');
INSERT INTO `scope` VALUES (2, 'read');
INSERT INTO `scope` VALUES (3, 'write');
INSERT INTO `scope` VALUES (4, 'all');
INSERT INTO `scope` VALUES (5, 'read');
INSERT INTO `scope` VALUES (6, 'write');
INSERT INTO `user` VALUES (1, '', '', '', '', '$2a$10$j8Yeg2KnM1hVFXWXyRmTieSJp2Aef7RB9XysCK5gs2Uh27CLE8O/C', '使用默认加密，不需要存储密码盐', 'admin');
INSERT INTO `user_to_role` VALUES (1, 1);
INSERT INTO `user_to_role` VALUES (1, 2);
INSERT INTO `user_to_role` VALUES (1, 3);
